version: "3.8"
services:
  user:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - USER_NAME=user
        - GROUP_NAME=user
        - PASSWORD=user
    tty: true
    volumes:
      - type: bind
        source: ./Public
        target: $HOME/Public
