version: "3.8"
services:
  user:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - USER_NAME=yasunori
        - GROUP_NAME=yasunori
        - PASSWORD=yasunori
    tty: true
